name: Integration

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - run: yarn

    - run: yarn build

    - uses: actions/upload-artifact@v2
      with:
        path: build/stack.yml
